name: Left4Chat
main: me.sisko.left4chat.util.Main
version: 1.7
api-version: 1.17
depend: [Vault, LuckPerms, Nicky]
commands:
  discord:
    description: Syncs with Left4Craft Discord
    usage: /discord [code]
  announce:
    description: Sends a message to the entire network
    usage: /announce <message>
  game:
    description: Opens a GUI to change servers
    usage: /game
  msg:
    description: Messages other players cross-server
    usage: /msg <player> <message>
    aliases: [m, tell, pm, message, w, whisper]
  reply:
    description: Replies to the last received message
    usage: /reply <message>
    aliases: [r]
  afk:
    description: Toggles afk status
    usage: /afk
  ggivecosmetic:
    description: Global give cosmetic command
    usage: /ggivecosmetic <name> <amount> [tier]
  verify:
    description: Verifies a user account
    usage: /verify
  chatlock:
    description: Locks down the chat, requiring everyone to verify
    usage: /chatlock
  chatreload:
    description: Reloads the Left4Chat plugin
    usage: /chatreload
  list:
    description: List online players
    usage: /list
    